In [27]:
import pandas as pd
import pickle
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F 
import copy
import math

from tqdm import tqdm

In [28]:
dtype = {
    'userID': 'int16',
    'answerCode': 'int8',
    'KnowledgeTag': 'int16'
}   

In [29]:
TEST_DATA_PATH = '/opt/ml/input/data/train_dataset/test_all_three.csv'
test_df = pd.read_csv(TEST_DATA_PATH, dtype=dtype, parse_dates=['Timestamp'])
test_df = test_df.sort_values(by=['userID', 'Timestamp']).reset_index(drop=True)

In [30]:
test_df.head()

userID assessmentItemID      testId  answerCode           Timestamp  \
0       3       A050023001  A050000023           1 2020-01-09 10:56:31   
1       3       A050023002  A050000023           1 2020-01-09 10:56:57   
2       3       A050023003  A050000023           0 2020-01-09 10:58:31   
3       3       A050023004  A050000023           0 2020-01-09 10:58:36   
4       3       A050023006  A050000023           0 2020-01-09 10:58:43   

   KnowledgeTag  elapsed  
0          2626     26.0  
1          2626     94.0  
2          2625      5.0  
3          2625      7.0  
4          2623      3.0

In [31]:
test_df['UID']=test_df['userID'].apply(lambda x:str(x).zfill(6))+test_df['testId']

In [32]:
test_df.head()

userID assessmentItemID      testId  answerCode           Timestamp  \
0       3       A050023001  A050000023           1 2020-01-09 10:56:31   
1       3       A050023002  A050000023           1 2020-01-09 10:56:57   
2       3       A050023003  A050000023           0 2020-01-09 10:58:31   
3       3       A050023004  A050000023           0 2020-01-09 10:58:36   
4       3       A050023006  A050000023           0 2020-01-09 10:58:43   

   KnowledgeTag  elapsed               UID  
0          2626     26.0  000003A050000023  
1          2626     94.0  000003A050000023  
2          2625      5.0  000003A050000023  
3          2625      7.0  000003A050000023  
4          2623      3.0  000003A050000023

In [36]:
#userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,elapsed
group = test_df[list(test_df.columns)].groupby('UID').apply(
                lambda r: (
                    r['answerCode'].values,
                    r['assessmentItemID'].values, 
                    r['testId'].values,
                    r['Timestamp'].values,
                    r['KnowledgeTag'].values,
                    r['elapsed'].values,
                )
            )

In [37]:
group[0]

(array([1, 1, 1, 1, 0], dtype=int8),
 array(['A020001001', 'A020001002', 'A020001003', 'A020001004',
        'A020001005'], dtype=object),
 array(['A020000001', 'A020000001', 'A020000001', 'A020000001',
        'A020000001'], dtype=object),
 array(['2020-03-12T00:59:09.000000000', '2020-03-12T00:59:25.000000000',
        '2020-03-12T00:59:34.000000000', '2020-03-12T01:00:19.000000000',
        '2020-03-12T01:01:13.000000000'], dtype='datetime64[ns]'),
 array([7916, 7916, 7916, 7916, 7916], dtype=int16),
 array([16.       ,  9.       , 45.       , 54.       , 45.7140266]))

In [40]:
for idx,g in enumerate(group):
    if idx<15:
        print(g)

(array([1, 1, 1, 1, 0], dtype=int8), array(['A020001001', 'A020001002', 'A020001003', 'A020001004',
       'A020001005'], dtype=object), array(['A020000001', 'A020000001', 'A020000001', 'A020000001',
       'A020000001'], dtype=object), array(['2020-03-12T00:59:09.000000000', '2020-03-12T00:59:25.000000000',
       '2020-03-12T00:59:34.000000000', '2020-03-12T01:00:19.000000000',
       '2020-03-12T01:01:13.000000000'], dtype='datetime64[ns]'), array([7916, 7916, 7916, 7916, 7916], dtype=int16), array([16.       ,  9.       , 45.       , 54.       , 45.7140266]))
(array([1, 1, 1, 1, 1], dtype=int8), array(['A020005001', 'A020005002', 'A020005003', 'A020005004',
       'A020005005'], dtype=object), array(['A020000005', 'A020000005', 'A020000005', 'A020000005',
       'A020000005'], dtype=object), array(['2020-03-03T07:37:10.000000000', '2020-03-03T07:37:32.000000000',
       '2020-03-03T07:37:38.000000000', '2020-03-03T07:37:44.000000000',
       '2020-03-03T07:38:17.000000000'], dtype=

In [41]:
z_d = test_df.groupby(['UID'])['answerCode'].agg(['min']).to_dict()

In [49]:
test_df["min"]=test_df.UID.map(z_d['min'])

In [50]:
test_df.head()

userID assessmentItemID      testId  answerCode           Timestamp  \
0       3       A050023001  A050000023           1 2020-01-09 10:56:31   
1       3       A050023002  A050000023           1 2020-01-09 10:56:57   
2       3       A050023003  A050000023           0 2020-01-09 10:58:31   
3       3       A050023004  A050000023           0 2020-01-09 10:58:36   
4       3       A050023006  A050000023           0 2020-01-09 10:58:43   

   KnowledgeTag  elapsed               UID  min  
0          2626     26.0  000003A050000023    0  
1          2626     94.0  000003A050000023    0  
2          2625      5.0  000003A050000023    0  
3          2625      7.0  000003A050000023    0  
4          2623      3.0  000003A050000023    0

In [61]:
ret=test_df[test_df['min']==-1]
ret.reset_index(drop=True)

userID assessmentItemID      testId  answerCode           Timestamp  \
0          3       A050133001  A050000133           1 2020-10-26 13:08:41   
1          3       A050133002  A050000133           1 2020-10-26 13:09:28   
2          3       A050133003  A050000133           1 2020-10-26 13:10:22   
3          3       A050133004  A050000133           1 2020-10-26 13:12:11   
4          3       A050133005  A050000133           1 2020-10-26 13:12:36   
...      ...              ...         ...         ...                 ...   
4832    7439       A040130001  A040000130           0 2020-10-14 23:07:23   
4833    7439       A040130002  A040000130           1 2020-10-14 23:07:41   
4834    7439       A040130003  A040000130           1 2020-10-14 23:08:02   
4835    7439       A040130004  A040000130           1 2020-10-14 23:09:31   
4836    7439       A040130005  A040000130          -1 2020-10-14 23:10:03   

      KnowledgeTag    elapsed               UID  min  
0             5288   47.00000  000003A050000133   -1  
1             5288   54.00000  000003A050000133   -1  
2             5289  109.00000  000003A050000133   -1  
3             5289   25.00000  000003A050000133   -1  
4             5288   16.00000  000003A050000133   -1  
...            ...        ...               ...  ...  
4832          8832   18.00000  007439A040000130   -1  
4833          8832   21.00000  007439A040000130   -1  
4834          8244   89.00000  007439A040000130   -1  
4835          8244   32.00000  007439A040000130   -1  
4836          8832   27.56193  007439A040000130   -1  

[4837 rows x 9 columns]

In [62]:
len(ret.groupby("UID"))

744

In [63]:
ret.head(50)

userID assessmentItemID      testId  answerCode           Timestamp  \
1028       3       A050133001  A050000133           1 2020-10-26 13:08:41   
1029       3       A050133002  A050000133           1 2020-10-26 13:09:28   
1030       3       A050133003  A050000133           1 2020-10-26 13:10:22   
1031       3       A050133004  A050000133           1 2020-10-26 13:12:11   
1032       3       A050133005  A050000133           1 2020-10-26 13:12:36   
1033       3       A050133006  A050000133           1 2020-10-26 13:12:52   
1034       3       A050133007  A050000133           0 2020-10-26 13:13:11   
1035       3       A050133008  A050000133          -1 2020-10-26 13:13:57   
1699       4       A070146001  A070000146           1 2020-12-27 02:45:02   
1700       4       A070146002  A070000146           1 2020-12-27 02:45:13   
1701       4       A070146003  A070000146           0 2020-12-27 02:45:46   
1702       4       A070146004  A070000146           1 2020-12-27 02:46:11   
1703       4       A070146005  A070000146           1 2020-12-27 02:46:36   
1704       4       A070146006  A070000146           1 2020-12-27 02:46:51   
1705       4       A070146007  A070000146           1 2020-12-27 02:47:31   
1706       4       A070146008  A070000146          -1 2020-12-27 02:47:54   
3016      13       A070111001  A070000111           0 2020-12-27 04:33:25   
3017      13       A070111002  A070000111           1 2020-12-27 04:33:50   
3018      13       A070111003  A070000111           1 2020-12-27 04:34:31   
3019      13       A070111004  A070000111           0 2020-12-27 04:34:50   
3020      13       A070111005  A070000111           0 2020-12-27 04:34:55   
3021      13       A070111006  A070000111           0 2020-12-27 04:34:59   
3022      13       A070111007  A070000111           1 2020-12-27 04:35:01   
3023      13       A070111008  A070000111          -1 2020-12-27 04:35:09   
4278      17       A090064001  A090000064           1 2020-10-30 05:42:17   
4279      17       A090064002  A090000064           1 2020-10-30 05:43:18   
4280      17       A090064003  A090000064           1 2020-10-30 05:44:52   
4281      17       A090064004  A090000064           1 2020-10-30 05:45:36   
4282      17       A090064005  A090000064           1 2020-10-30 05:47:22   
4283      17       A090064006  A090000064          -1 2020-10-30 05:48:37   
4664      26       A060135001  A060000135           1 2020-10-23 11:39:43   
4665      26       A060135002  A060000135           1 2020-10-23 11:40:06   
4666      26       A060135003  A060000135           1 2020-10-23 11:42:57   
4667      26       A060135004  A060000135           0 2020-10-23 11:43:24   
4668      26       A060135005  A060000135           1 2020-10-23 11:43:45   
4669      26       A060135006  A060000135           0 2020-10-23 11:44:01   
4670      26       A060135007  A060000135          -1 2020-10-23 11:44:18   
5520      29       A020190001  A020000190           1 2020-10-22 04:37:01   
5521      29       A020190002  A020000190           1 2020-10-22 04:37:17   
5522      29       A020190003  A020000190           1 2020-10-22 04:37:54   
5523      29       A020190004  A020000190           1 2020-10-22 04:38:15   
5524      29       A020190005  A020000190          -1 2020-10-22 04:38:45   
6604      45       A040136001  A040000136           1 2020-10-23 08:22:39   
6605      45       A040136002  A040000136           0 2020-10-23 08:24:03   
6606      45       A040136003  A040000136           0 2020-10-23 08:24:14   
6607      45       A040136004  A040000136           0 2020-10-23 08:24:15   
6608      45       A040136005  A040000136          -1 2020-10-23 08:24:19   
7297      53       A040140001  A040000140           1 2020-10-26 09:12:39   
7298      53       A040140002  A040000140           1 2020-10-26 09:12:50   
7299      53       A040140003  A040000140           0 2020-10-26 09:12:53   

      KnowledgeTag     elapsed               UID  min  
1028          5288   4

In [64]:
del ret['min']

In [65]:
ret.head()

userID assessmentItemID      testId  answerCode           Timestamp  \
1028       3       A050133001  A050000133           1 2020-10-26 13:08:41   
1029       3       A050133002  A050000133           1 2020-10-26 13:09:28   
1030       3       A050133003  A050000133           1 2020-10-26 13:10:22   
1031       3       A050133004  A050000133           1 2020-10-26 13:12:11   
1032       3       A050133005  A050000133           1 2020-10-26 13:12:36   

      KnowledgeTag  elapsed               UID  
1028          5288     47.0  000003A050000133  
1029          5288     54.0  000003A050000133  
1030          5289    109.0  000003A050000133  
1031          5289     25.0  000003A050000133  
1032          5288     16.0  000003A050000133

In [66]:
ret.to_csv('/opt/ml/input/data/train_dataset/test_uid.csv',index=False)

In [67]:
TRAIN_DATA_PATH = '/opt/ml/input/data/train_dataset/train_all_three.csv'
train_df = pd.read_csv(TRAIN_DATA_PATH, dtype=dtype, parse_dates=['Timestamp'])
train_df = train_df.sort_values(by=['userID', 'Timestamp']).reset_index(drop=True)

In [68]:
train_df['UID']=train_df['userID'].apply(lambda x:str(x).zfill(6))+train_df['testId']

In [69]:
train_df.head()

userID assessmentItemID      testId  answerCode           Timestamp  \
0       0       A060001001  A060000001           1 2020-03-24 00:17:11   
1       0       A060001002  A060000001           1 2020-03-24 00:17:14   
2       0       A060001003  A060000001           1 2020-03-24 00:17:22   
3       0       A060001004  A060000001           1 2020-03-24 00:17:29   
4       0       A060001005  A060000001           1 2020-03-24 00:17:36   

   KnowledgeTag  elapsed               UID  
0          7224      3.0  000000A060000001  
1          7225      8.0  000000A060000001  
2          7225      7.0  000000A060000001  
3          7225      7.0  000000A060000001  
4          7225     11.0  000000A060000001

In [70]:
train_df.to_csv('/opt/ml/input/data/train_dataset/train_uid.csv',index=False)